/**
 * This is ported from lba2_body.hqd from LBArchitect
 */
module.exports = {
  0: "Twinsen without tunic model",
  1: "Twinsen with tunic model",
  2: "Twinsen with tunic and sword model",
  3: "Twinsen with tunic and blowgun model",
  4: "Twinsen with tunic and blowtron model",
  5: "Twinsen with tunic and wannie glove model",
  6: "Twinsen with tunic and laser pistol model",
  7: "Twinsen with wizard's tunic model",
  8: "Twinsen with wizard's tunic and blowgun model",
  9: "Twinsen with tunic (darker shading) model",
  10: "Twinsen with tunic (darker shading) and pick-axe model",
  11: "Twinsen with tunic (darker shading) and portable radio model",
  12: "Twinsen burning model",
  13: "Twinsen falling in Dome of the Slate model",
  14: "Twinsen with tunic and car closed model",
  15: "Twinsen with wizard's tunic and car closed model",
  16: "Twinsen with tunic and protopack model",
  17: "Twinsen with tunic and Zoé model",
  18: "Twinsen with tunic and Horn of Blue Triton model",
  19: "Twinsen with wizard's tunic and Horn of Blue Triton model",
  20: "Twinsen with space suit model",
  21: "Twinsen with tunic and super jetpack model",
  22: "Twinsen with tunic and car open model",
  23: "Twinsen with wizard's tunic and car open model",
  24: "Twinsen X-Rayed model",
  25: "Nitro-meca-penguin model",
  26: "Zoé model",
  27: "Zoé with umbrella model",
  28: "Piece of flying saucer model",
  29: "Dot model",
  30: "Holomap model",
  31: "Three darts model",
  32: "Raph, the lighthouse keeper model",
  33: "The Tralu model",
  34: "Snake model",
  35: "Rabbibunny skeleton model",
  36: "The flying rat model",
  37: "The quetch not being from Citadel Island model",
  38: "Drunk rabbibunny in Luc's bar model",
  39: "Luc, the boss model",
  40: "Tim, waiter model",
  41: "A sphero (Raph's friend) model",
  42: "Another sphero model",
  43: "A third sphero model",
  44: "Quetch girl, Raph's friend model",
  45: "Quetch girl, Raph's friend model",
  46: "Sup in light green dressing model",
  47: "Sup in light green dressing with gun model",
  48: "Sup in light green dressing with newspaper model",
  49: "Yellow franco with green pistol model",
  50: "Yellow franco with red pistol model",
  51: "Gray esmer dog without mouth protection model",
  52: "Gray esmer dog with mouth protection model",
  53: "Brown esmer dog without mouth protection model",
  54: "Grobo in the baggage claim model",
  55: "Propeller of the crate-moving apparatus model",
  56: "Rabbibunny in the baggage claim model",
  57: "Crate-pushing apparatus model",
  58: "Quetch in the baggage claim model",
  59: "Mr. Paul model",
  60: "Grobo no. 1 in Temple of Bù model",
  61: "Quetch in the Inter-Islands Ferry (Cit. Island) model",
  62: "Mrs. Brune (Inter-Islands rabbibunny) model",
  63: "Neighbor without gallic acid model",
  64: "Neighbor with gallic acid model",
  65: "Cart in Temple of Bù model",
  66: "Arrow in Temple of Bù model",
  67: "Painter from Citadel Island sewers model",
  68: "Rabbibunny in blue-white dressing model",
  69: "Nitro-Meca-Penguin model",
  70: "Flying saucer (UFO) with closed door and lights off model",
  71: "Flying saucer (UFO) with quarter-open door model",
  72: "Flying saucer (UFO) with closed door and lights on model",
  73: "Flying saucer (UFO) with closed door, lights on, and feet out model",
  74: "Royal saucer (UFO) with quarter-open door model",
  75: "Royal saucer (UFO) with closed door model",
  76: "Royal saucer (UFO) with closed door and feet in model",
  77: "Royal saucer (UFO) with closed door and feet out model",
  78: "Small flying saucer (UFO) model",
  79: "Boat is Esmers' secret base model",
  80: "Franco guard with spike model",
  81: "Franco guard with spike model",
  82: "Franco guard with spike model",
  83: "Franco guard with spike model",
  84: "Sup in dark green dressing (clone of Johnny Rocket) model",
  85: "Sup in red dressing model",
  86: "Franco policeman with red helmet and gun model",
  87: "Franco policeman with black hat and gun model",
  88: "X-rayed franco red-helmet policeman model",
  89: "Franco policeman with green hat and stick model",
  90: "Franco survivor from Island CX model",
  91: "Yellow-red franco guard dressing (from secret base) model",
  92: "Baldino with space suit without helmet model",
  93: "Baldino with space suit with helmet in hand model",
  94: "Baldino with space suit with helmet model",
  95: "Light gray franco guard model",
  96: "Franco dissident model",
  97: "Light gray franco guard with gun model",
  98: "Light gray franco guard with tool model",
  99: "Mr. Bazoo (grobo in shop on Citadel Island) model",
  100: "Clerk in Mrs. Bloop's museum model",
  101: "Quetch guard of Temple Park model",
  102: "Quetch visitor of Mrs. Bloop's museum model",
  103: "Quetch guard of Temple Park with umbrella model",
  104: "Mrs. Bloop model",
  105: "Container in museum with Tunic model",
  106: "Container in museum without Tunic model",
  107: "Trunk in the sewers model",
  108: "Bird on Citadel Island model",
  109: "Little Tralu model",
  110: "Joe the Elf model",
  111: "Weather wizard model",
  112: "Creature in weather wizard's stove model",
  113: "Pharmacist model",
  114: "Sphero customer of pharmacy model",
  115: "Sphero customer of pharmacy with vacuum cleaner model",
  116: "Sphero customer of pharmacy with umbrella model",
  117: "The Citadel Island thief model",
  118: "The Citadel Island thief with customer's umbrella model",
  119: "Nomad grobo from Desert Island model",
  120: "A quetch model",
  121: "Female rabbibunny in swimming costume (in Hacienda bath) model",
  122: "Female grobo in Hacienda bath model",
  123: "Dean of the School of Magic model",
  124: "Female rabbibunny in the School of Magic model",
  125: "Ghost in the School of Magic model",
  126: "Sad grobo student in the School of Magic model",
  127: "Black nomad sphero from Desert Island model",
  128: "Male grobo in Hacienda bath model",
  129: "Empty space suit model",
  130: "Blowgun test magic symbol in the School of Magic model",
  131: "Hourglass (blowgun test) model",
  132: "Flask of gallic acid model",
  133: "Rabbibunny in shop on Desert Island model",
  134: "Rabbibunny child model",
  135: "Teacher of the kindergarten on Citadel Island model",
  136: "Grobo child model",
  137: "Quetch child 1 model",
  138: "Quetch child 2 with rope model",
  139: "Jerome Baldino model",
  140: "Memory viewer model",
  141: "Notes model",
  142: "Grobo in the hotel on Desert Island model",
  143: "Sub in blue dressing in the flying saucer model",
  144: "Female sup in the flying saucer model",
  145: "Female sup in the flying saucer with pull bell model",
  146: "Female sup in the flying saucer with pull bell and safety jacket model",
  147: "The translator model",
  148: "Rabbibunny with motorbike model",
  149: "Rabbibunny with motorbike and Twinsen with Tunic model",
  150: "Rabbibunny with motorbike and Twinsen with Wizard's Tunic model",
  151: "Bob with covered head model",
  152: "Bob with uncovered head model",
  153: "Sup in dark green dressing (clone of Johnny Rocket) model",
  154: "Johnny Rocket model",
  155: "Johnny Rocket in pyjamas model",
  156: "Elevator (big) model",
  157: "Robot on Otringal (prison guard) model",
  158: "Robot on Desert Island model",
  159: "Robot on Citadel Island model",
  160: "Felix with covered head model",
  161: "Felix with uncovered head model",
  162: "Crab model",
  163: "Top of giant crab model",
  164: "Front scissors (or feet) of giant crab model",
  165: "Ferry (you can call it hovercraft) model",
  166: "Dino-Fly with Twinsen with Tunic model",
  167: "Dino-Fly model",
  168: "Dino-Fly with Twinsen with Wizard's Tunic model",
  169: "Zed model",
  170: "Quetch, in love with the pharmacist model",
  171: "Mushroom model",
  172: "Raph's fiance model",
  173: "Piece of giant crab's scissor (or foot) model",
  174: "Light from a lighthouse model",
  175: "Twinsen and Zoé with the umbrella down model",
  176: "Quetch child 2 without rope model",
  177: "Rosa the cow model",
  178: "Quetch child 3 (on top of the pharmacy) model",
  179: "Quetch child 3 without his head model",
  180: "Quetch in black dressing (Quetch child 1's big brother) model",
  181: "Trash can (hidden Esmer) 1 model",
  182: "Trash can (hidden Esmer) 2 model",
  183: "The Citadel Island thies with his sister (Rabbibunny child) model",
  184: "The teacher of the kindergarten with Quetch child 2 model",
  185: "Luc, the boss, with his brother (Grobo child) model",
  186: "Franco guy with plates model",
  187: "Franco guy with glass model",
  188: "Sphero wizard (Ker'aooc) model",
  189: "Female quetch wizard (Tabata)",
  190: "Grobo wizard model",
  191: "The usually drunk franco guy model",
  192: "Mosquibee guy 1 model",
  193: "Mosquibee guy 2 model",
  194: "Wannie guy 1 model",
  195: "Wannie guy 2 model",
  196: "Queen of the Mosquibees model",
  197: "Mosquibee Queen's ventilation guy model",
  198: "Quetch child #3 with plate with piece of cake model",
  199: "Female rabbibunny in the School of Magic model",
  200: "Sup sailor with glass model",
  201: "Twinsen with Tunic with piece of cake model",
  202: "Mosquibee guy with containe full of liquid model",
  203: "Zoé not pregnant anymore with child-carry thing 1 model",
  204: "Zoé not pregnant anymore with child-carry thing 2 model",
  205: "Franco nurse with franco child 1 model",
  206: "Franco child 2 model",
  207: "Wannie child 1 model",
  208: "Zed on the beach model",
  209: "Control-wheel for the woodbridge model",
  210: "Woodbridge transport wood model",
  211: "Giand spider (Citadel Island cliffs) model",
  212: "Moya the turtle model",
  213: "Silhuette of the turtle model",
  214: "The turtle slightly rising model",
  215: "The turtle greatly rising model",
  216: "The turtle almost out model",
  217: "Cactus (hidden Esmer) model",
  218: "The turtle-calling bell model",
  219: "Empty car model",
  220: "Clover box model",
  221: "One of the many desert flowers model",
  222: "Desert sphero 1 model",
  223: "Desert sphero 1 with guitar model",
  224: "Desert sphero 2 model",
  225: "Camel 1 model",
  226: "Camel 2 model",
  227: "Car with racer model",
  228: "Sphero bowl player model",
  229: "Quetch bowl player model",
  230: "Ball 1 (big gray ball) model",
  231: "Ball 2 (small red ball) model",
  232: "Quetch girl in swimming costume with book model",
  233: "Franco guy with beard (bowl player) model",
  234: "Sup in light green dressing (bowl player) model",
  235: "Quetch guard of Temple Park model",
  236: "Sup guy in swimming costume (Imerial Hotel) model",
  237: "Green shell (Joe the Elf imprisoned) model",
  238: "The Eye 1 of the School of Magic model",
  239: "The Eye 2 of the School of Magic model",
  240: "Chedil Amiradoo model",
  241: "The balsam flower model",
  242: "Piece of a plant model",
  243: "The sphero near Port-Ludo model",
  244: "Grobo policeman, guard of Temple Park model",
  245: "Rabbibunny, don't know, where he appears model",
  246: "Small yellow duck model",
  247: "Twinsen with Tunic and balloons model",
  248: "Twinsen with Wizard's Tunic and balloons model",
  249: "The balloons model",
  250: "Desert grobo model",
  251: "Old rabbibunny with guitar model",
  252: "Old rabbibunny with magic flute model",
  253: "The chest with old rabbibunny's domestic snake model",
  254: "The chest empty model",
  255: "Sup in space suit model",
  256: "Giraffe guy with camera on Zeelich model",
  257: "Ant guy with backpack on Zeelich model",
  258: "Ant guy 2 on Zeelich model",
  259: "Two-headed monster in Emperor's palace model",
  260: "Emperor's sup soldier 1 model",
  261: "Emperor's sup soldier 2 model",
  262: "Sup in swimming costume in water model",
  263: "Old sup lady in Imperial Hotel model",
  264: "Franco guard in Imperial Hotel model",
  265: "Franco policeman with stick down model",
  266: "Franco policeman with stick in hand model",
  267: "Female franco model",
  268: "Narrow electric barrier model",
  269: "Wider electric barrier model",
  270: "Mosquibee dissident model",
  271: "Sup guard of Emperor's palace model",
  272: "Sup guard of Emperor's palace with sword out model",
  273: "Leontine (zeppelin-boat of the old franco) model",
  274: "Leontine with the old franco aboard model",
  275: "Leontine with the old franco and Twinsen aboard model",
  276: "The old franco model",
  277: "Driver 1 of the motor-flyer model",
  278: "Driver 2 of the motor-flyer model",
  279: "The motor-flyer model",
  280: "Motor-flyer with driver 1 aboard model",
  281: "Motor-flyer with driver 1 and Twinsen aboard model",
  282: "Motor-flyer with driver 2 aboard model",
  283: "Motor-flyer with driver 2 and Twinsen aboard model",
  284: "Open crate in the undergas center model",
  285: "Closed crate in the undergas center model",
  286: "Open crate in the undergas center with Twinsen inside model",
  287: "Small closed crate model",
  288: "Franco policeman with red hat and gun on the car model",
  289: "Shotgun model",
  290: "Franco trooper model",
  291: "Franco trooper with UZI model",
  292: "Sup priest model",
  293: "Franco at the gas station on Otringal with gas-piston model",
  294: "Franco at the gas station on Otringal with hammer model",
  295: "Green gloom (alligator) model",
  296: "Green gloom (alligator) with tie model",
  297: "Gray gloom (alligator) model",
  298: "Small gloom (alligator), casino exit guard model",
  299: "Big gray gloom (alligator), holding Twinsen model",
  300: "Big gray gloom (alligator) model",
  301: "Franco with drum model",
  302: "Car at the gas station on Otringal model",
  303: "Zeelichian car without the gun model",
  304: "The gun of the car model",
  305: "Dark Monk's key model",
  306: "Fire ball model",
  307: "Franco survivor from Island CX model",
  308: "Kangaroo 1 model",
  309: "Kangaroo 2 model",
  310: "Franco priest model",
  311: "Dark Monk (hidden FunFrock) model",
  312: "FunFrock unihidding himself model",
  313: "Unhidden FunFrock model",
  314: "Unhidden FunFrock with sword out model",
  315: "Teleporting FunFrock model",
  316: "Standing stone 1 (for lava) model",
  317: "Standing stone 2 (for lava) model",
  318: "Mosquibee guy with beard model",
  319: "Wannie priest model",
  320: "Gas monster 1 model",
  321: "Silhuette of gas monster's head 1 model",
  322: "Gas monster 2 model",
  323: "Wannie guy 1 model",
  324: "Wannie guy 2 model",
  325: "Wannie guy 3 model",
  326: "Wannie guy 4 model",
  327: "Wannie child model",
  328: "Wannie child with red ball model",
  329: "Wannie grandma model",
  330: "Wannie grandma with plate with piece of tart model",
  331: "Wannie child capturing fireflies model",
  332: "Firefly model",
  333: "Frog model",
  334: "Ferryman with boat model",
  335: "Ferryman with boat with Twinsen aboard model",
  336: "Wannie guy 5 model",
  337: "Gem model",
  338: "Elevator to the undergas model",
  339: "Elevator to the undergas with Twinsen inside model",
  340: "Small gas monster 1 (blue) model",
  341: "Small gas monster 2 (gray) model",
  342: "Wannie guy with pick-axe model",
  343: "Undergas bulldozer model",
  344: "Undergas bulldozer pick-thing part 1 model",
  345: "Undergas bulldozer pick-thing part 2 model",
  346: "Little yellow pig model",
  347: "Main train wagon with wannie inside model",
  348: "Train wagon model",
  349: "Train wagon with stones model",
  350: "100% Firefly tart model",
  351: "5/6 Firefly tart model",
  352: "3/4 Firefly tart model",
  353: "2/3 Firefly tart model",
  354: "Wannie child's red ball model",
  355: "Wannie's glove model",
  356: "Gas monster 3 (gray) model",
  357: "Glass plate model",
  358: "Cover of the box with the mosquibees key fragment model",
  359: "Green mosquibee guy model",
  360: "Franco trooper with explosive box model",
  361: "Green mosquibee guy with flag model",
  362: "Mosquibee guy with Twinsen model",
  363: "Monkey monster with sword model",
  364: "Franco trooper with parachute model",
  365: "Mosquibee flag model",
  366: "Emperor's flag model",
  367: "Rope to get into the mosquibee fortress model",
  368: "Rope to get into the mosquibee fortress with Twinsen model",
  369: "Franco trooper with UZI and explosive ball model",
  370: "The two-zeppelin transport method to the elevator model",
  371: "Female dog on the Island of the Francos model",
  372: "Franco worker on the Island of the Francos model",
  373: "Franco with metal-detector on the Island of the Francos model",
  374: "Franco worker with red hat on the Island of the Francos model",
  375: "Mechanic owl model",
  376: "Gas monster 4 model",
  377: "Rocket-shooter on Island CX model",
  378: "Wannie guy with one glove model",
  379: "Sup in orange dressing (in Imperial Hotel and saucer) model",
  380: "Sup getting in garbage can in saucer model",
  381: "Sup getting in cactus in saucer model",
  382: "Wannie guy digging model",
  383: "Wannie child #1's toys model",
  384: "The wannies key fragment model",
  385: "Spider net model",
  386: "Old wannie model",
  387: "Old wannie with piece of tart model",
  388: "Monkey monster model",
  389: "Monkey monster with wooden box model",
  390: "Wannie child with captured firefly model",
  391: "'Feet' for something 1 model",
  392: "'Feet' for something 2 model",
  393: "Sup 1 with cigar in the undergas agency model",
  394: "Sup 2 sitting down with papers in the undergas agency model",
  395: "Gray ball model",
  396: "Fat yellow/black mosquibee guy model",
  397: "Blowtron model",
  398: "Green mosquibee guy with red flag model",
  399: "Lava fire ball model",
  400: "The wheel of fortune model",
  401: "Big gray gloom (alligator) with big stick model",
  402: "Female franco dancer model",
  403: "Franco fireman model",
  404: "Sup heavy metal guy in black dressing model",
  405: "Female franco dancer model",
  406: "The reptile-thing in the casino (come to papa) model",
  407: "Brown dog in the casino model",
  408: "Orange dog in the casino model",
  409: "Cyan dog in the casino model",
  410: "Yellow dog in the casino model",
  411: "Sup 1 in the casino model",
  412: "Sup 2 in the casino model",
  413: "Green gloom (alligator) 1 in the casino model",
  414: "Green gloom (alligator) 2 in the casino model",
  415: "Sailor (maybe pink wannie) 1 model",
  416: "Sailor (maybe pink wannie) 1 with gun model",
  417: "Glass of drink model",
  418: "Sailor (maybe pink wannie) 2 model",
  419: "Sailor (maybe pink wannie) 3 model",
  420: "Sailor (maybe brown wannie) model",
  421: "Sup sailor with glass of drink model",
  422: "Young wannie with stone in front of him model",
  423: "Half of a franco sitting down model",
  424: "Franco with gray hat and glass model",
  425: "Rick the sup model",
  426: "Silhuette of gas monster's head 2 model",
  427: "Gas monster 5 model",
  428: "Female franco model",
  429: "Can of gazogem model",
  430: "Sup 1 in the shop (I love Twinsun) model",
  431: "Sup 2 in the shop (I hate Twinsun) model",
  432: "Wizard's diploma model",
  433: "Ferry ticket model",
  434: "Customer's umbrella model",
  435: "Small spider model",
  436: "Pighead in red dressing with hammer (Emperor's palace) model",
  437: "Pighead in brown dressing with gardening tool (Emperor's palace) model",
  438: "Pighead in yellow dressing with broom (Emperor's palace) model",
  439: "Stan (from Time Commando) model",
  440: "Shy sup girl in Imperial Hotel model",
  441: "Light gray franco guard listening to music in Imperial Hotel model",
  442: "The above franco's tape player model",
  443: "Female franco in the shop on the Island of the Francos model",
  444: "Pick-axe model",
  445: "Glass-cleaning (at least I think) franco model",
  446: "Old franco scientist model",
  447: "Female franco nurse in the nursery model",
  448: "Franco child with red rapper hat model",
  449: "A small franco child modeld",
  450: "Brother of francos' burgermaster (De La Fontaine) model",
  451: "Gas monster 6 (gray) model",
  452: "Silhuette of gas monster's head 3 model",
  453: "The emperor model",
  454: "The emperor's wife model",
  455: "Spikes in the protection spell's cave model",
  456: "Monster guarding the protection spell model",
  457: "The protection spell model",
  458: "Vertical electric bar of teleporting machine model",
  459: "Gray mechanic grobo near the end model",
  460: "Green mechanic grobo with box of missiles near the end model",
  461: "Quetch child 1 model",
  462: "Very long and thin vertical piece of metal model",
  463: "Two such pieces of metal model",
  464: "Grobo child model",
  465: "Rabbibunny child model",
  466: "Quetch child 2 model",
  467: "Extremely long and thin vertical/horizontal pieces of metal model",
  468: "Mechanic rabbibunny near the end model",
};
